apiVersion: apps/v1
kind: Deployment
metadata:
    name: angularfe-app-deployment
    namespace: public-dikshasingla
    labels:
        app: angularfe-app
spec:
    replicas: 3
    selector:
        matchLabels:
            app: angularfe-app
    template:
        metadata:
            labels:
                app: angularfe-app
        spec:
            containers:
                - name: angularfe-app
                  image: dikshasingla/angularfe:1
                  ports:
                    - name: http
                      containerPort: 80
                      protocol: TCP
