apiVersion: v1
kind: Service
metadata: 
    name: angularfe-app
    namespace: public-dikshasingla
    labels:
        app: angularfe-app
spec:
    type: LoadBalancer
    selector:
        app: angularfe-app
    ports:
        - protocol: TCP
          nodePort: 30159
          port: 8888
          targetPort: 80